"use client";
import { useMemo, useState } from "react";
import { Bell, CalendarDays, ChevronRight, CircleDollarSign, CreditCard, LayoutDashboard, LogOut, MoreHorizontal, Plus, ReceiptText, Settings, Users, WalletCards } from "lucide-react";
import { logout, markPaid } from "@/app/actions";
import { money, monthLabel, shortDate } from "@/lib/format";
import { TransactionForm } from "@/components/transaction-form";

type DashboardProps = { userName: string; accounts: { id: string; name: string; openingBalance: number; color: string }[]; cards: { id: string; name: string; color: string; creditLimit: number }[]; categories: { id: string; name: string }[]; transactions: { id: string; description: string; amount: number; status: string; category: string; card: { name: string; color: string } | null; responsiblePerson: string | null; dueDate: string | null; competenceDate: string }[]; forecast: { amount: number; competenceDate: string }[]; receivables: { person: string; amount: number }[] };

export function Dashboard({ userName, accounts, cards, categories, transactions, forecast, receivables }: DashboardProps) {
  const [adding, setAdding] = useState(false);
  const month = new Date();
  const expenses = transactions.filter(t => t.status !== "CANCELED" && t.status !== "REFUNDED").reduce((sum, t) => sum + t.amount, 0);
  const paid = transactions.filter(t => t.status === "PAID").reduce((sum, t) => sum + t.amount, 0);
  const receive = receivables.reduce((sum, item) => sum + item.amount, 0);
  const projections = useMemo(() => Array.from({ length: 6 }, (_, i) => { const date = new Date(month.getFullYear(), month.getMonth() + i, 1); const total = forecast.filter(t => new Date(t.competenceDate).getFullYear() === date.getFullYear() && new Date(t.competenceDate).getMonth() === date.getMonth()).reduce((sum, t) => sum + t.amount, 0); return { date, total }; }), [forecast]);
  const maxProjection = Math.max(...projections.map(p => p.total), 1);
  return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="mark">F</span><span>finora</span></div><nav><a className="active"><LayoutDashboard />Visão geral</a><a><ReceiptText />Lançamentos</a><a><WalletCards />Contas e cartões</a><a><Users />Pessoas</a><a><CalendarDays />Planejamento</a></nav><div className="sidebar-bottom"><a><Settings />Configurações</a><form action={logout}><button><LogOut />Sair</button></form></div></aside>
    <section className="content"><header className="topbar"><div><p className="eyebrow">VISÃO GERAL</p><h1>Olá, {userName.split(" ")[0]} <span>👋</span></h1><p className="muted">{monthLabel.format(month).replace(/^./, v => v.toUpperCase())} · Seu panorama financeiro</p></div><div className="top-actions"><button className="icon-button" aria-label="Notificações"><Bell size={19}/><i /></button><button className="avatar">{userName.slice(0, 1).toUpperCase()}</button><button className="button primary add-button" onClick={() => setAdding(true)}><Plus size={18}/>Novo lançamento</button></div></header>
      <section className="summary-grid"><Stat label="Comprometido este mês" value={money(expenses)} detail={`${transactions.length} lançamentos`} trend="base" icon={<ReceiptText/>}/><Stat label="Já foi pago" value={money(paid)} detail={expenses ? `${Math.round((paid / expenses) * 100)}% do mês` : "Sem pagamentos"} trend="positive" icon={<CircleDollarSign/>}/><Stat label="A receber" value={money(receive)} detail={`${receivables.length} pessoa${receivables.length === 1 ? "" : "s"} pendente${receivables.length === 1 ? "" : "s"}`} trend="accent" icon={<Users/>}/><Stat label="Cartões ativos" value={String(cards.length)} detail="Acompanhe limites e faturas" trend="neutral" icon={<CreditCard/>}/></section>
      <section className="main-grid"><div className="panel forecast"><div className="panel-header"><div><h2>Compromissos futuros</h2><p>Parcelas e despesas previstas</p></div><button className="text-button">Ver 12 meses <ChevronRight size={16}/></button></div><div className="chart">{projections.map((p, i) => <div className="bar-wrap" key={i}><strong>{money(p.total)}</strong><div className="bar-track"><div className="bar" style={{ height: `${Math.max((p.total/maxProjection)*100, p.total ? 8 : 2)}%` }} /></div><span>{p.date.toLocaleDateString("pt-BR", { month: "short" }).replace(".", "")}</span></div>)}</div><div className="forecast-note"><span>✦</span><p>Nos próximos 6 meses, você já tem <b>{money(projections.reduce((a, p) => a + p.total, 0))}</b> comprometidos.</p></div></div>
        <div className="panel cards-panel"><div className="panel-header"><div><h2>Seus cartões</h2><p>Limite planejado</p></div><button className="icon-button"><MoreHorizontal size={18}/></button></div>{cards.length ? cards.slice(0, 4).map((card, index) => { const used = transactions.filter(t => t.card?.name === card.name && t.status !== "PAID").reduce((sum, t) => sum + t.amount, 0); const pct = card.creditLimit ? Math.min((used/card.creditLimit)*100, 100) : 0; return <div className="card-row" key={card.id}><span className="card-symbol" style={{ background: card.color }}><CreditCard size={16}/></span><div><b>{card.name}</b><small>{card.creditLimit ? `${money(used)} de ${money(card.creditLimit)}` : "Limite não informado"}</small></div><div className="mini-progress"><i style={{ width: `${pct}%`, background: card.color }} /></div></div> }) : <Empty text="Cadastre seus cartões para acompanhar faturas." />}</div></section>
      <section className="panel transactions"><div className="panel-header"><div><h2>Próximos lançamentos</h2><p>O que vence ou está previsto neste mês</p></div><button className="text-button">Ver todos <ChevronRight size={16}/></button></div>{transactions.length ? <div className="transaction-list">{transactions.map(t => <div className="transaction-row" key={t.id}><span className="transaction-icon" style={{ background: t.card?.color || "#E8EEFF" }}>{t.card ? <CreditCard size={18}/> : <WalletCards size={18}/>}</span><div className="transaction-title"><b>{t.description}</b><small>{t.category}{t.responsiblePerson ? ` · ${t.responsiblePerson}` : ""}</small></div><span className="due">{t.dueDate ? `Vence ${shortDate.format(new Date(t.dueDate))}` : shortDate.format(new Date(t.competenceDate))}</span><strong>{money(t.amount)}</strong><span className={`status ${t.status.toLowerCase()}`}>{statusLabel(t.status)}</span>{t.status !== "PAID" && <button className="pay-button" onClick={() => markPaid(t.id)}>Marcar pago</button>}</div>)}</div> : <Empty text="Nada previsto neste mês. Crie seu primeiro lançamento." />}</section>
    </section>{adding && <TransactionForm accounts={accounts} cards={cards} categories={categories} onClose={() => setAdding(false)} />}</main>;
}

function Stat({ label, value, detail, trend, icon }: { label: string; value: string; detail: string; trend: string; icon: React.ReactNode }) { return <article className={`stat ${trend}`}><div className="stat-icon">{icon}</div><p>{label}</p><h2>{value}</h2><small>{detail}</small></article>; }
function Empty({ text }: { text: string }) { return <div className="empty">{text}</div>; }
function statusLabel(status: string) { return ({ PENDING: "Pendente", PLANNED: "Previsto", PAID: "Pago", OVERDUE: "Vencido", PARTIALLY_PAID: "Parcial" } as Record<string,string>)[status] || status; }
