"use client";

import { useActionState, useEffect, useMemo, useState, useTransition } from "react";
import { CircleAlert, Landmark, Plus, Scale, TrendingDown, X } from "lucide-react";
import { createDebt, registerDebtPayment, updateDebtStatus, type ActionState } from "@/app/actions";
import { projectDebt } from "@/lib/debt";
import { money } from "@/lib/format";

type Debt = { id: string; name: string; creditor: string | null; originalAmount: number; outstandingBalance: number; monthlyInterestRate: number; installmentAmount: number; minimumPayment: number | null; dueDay: number | null; remainingInstallments: number | null; status: string; notes: string | null; payments: { id: string; amount: number; paidAt: string; notes: string | null }[] };
type Indicator = { code: string; name: string; unit: string; date: string; value: number; source: string };

export function DebtPanel({ debts }: { debts: Debt[] }) {
  const [adding, setAdding] = useState(false);
  const [extra, setExtra] = useState<Record<string, string>>({});
  const [payment, setPayment] = useState<Record<string, string>>({});
  const [message, setMessage] = useState("");
  const [indicators, setIndicators] = useState<Indicator[]>([]);
  const [pending, startTransition] = useTransition();
  useEffect(() => { fetch("/api/reference/credit-rate").then((response) => response.ok ? response.json() : null).then((data) => setIndicators(data?.indicators || [])).catch(() => undefined); }, []);
  const active = debts.filter((item) => item.status !== "PAID");
  const total = active.reduce((sum, item) => sum + item.outstandingBalance, 0);
  const monthly = active.reduce((sum, item) => sum + item.installmentAmount, 0);
  const referenceFor = (debt: Debt) => indicators.find((item) => /cart[aã]o|rotativo/i.test(debt.name) ? item.code === "25477" : /cheque/i.test(debt.name) ? item.code === "25463" : /pessoal|empr[eé]stimo/i.test(debt.name) ? item.code === "25464" : item.code === "25435");
  function pay(debt: Debt) { const amount = Number(payment[debt.id]); if (!amount) return setMessage("Informe o valor pago."); startTransition(async () => { const result = await registerDebtPayment(debt.id, { amount }); setMessage(result.error || "Pagamento registrado e saldo atualizado."); if (!result.error) window.location.reload(); }); }
  function status(debt: Debt, value: "ACTIVE" | "NEGOTIATING" | "DEFAULTED") { startTransition(async () => { const result = await updateDebtStatus(debt.id, value); setMessage(result.error || "Situação da dívida atualizada."); if (!result.error) window.location.reload(); }); }
  return <div className="debt-layout"><section className="planning-head debt-head"><div><span className="kicker light">CENTRAL DE QUITAÇÃO</span><h2>{money(total)}</h2><p>saldo devedor cadastrado em {active.length} compromisso{active.length === 1 ? "" : "s"}</p></div><div><small>Parcelas mensais</small><strong>{money(monthly)}</strong><button className="button primary" onClick={() => setAdding(true)}><Plus />Nova dívida</button></div></section>
    {message && <div className="notice">{message}</div>}
    {!active.length && <section className="panel empty-action"><span><TrendingDown /></span><b>Nenhuma dívida ativa cadastrada</b><p>Cadastre saldo, parcela e juros para simular uma quitação responsável.</p><button className="button primary" onClick={() => setAdding(true)}>Cadastrar primeira dívida</button></section>}
    <section className="debt-grid">{active.map((debt) => { const projection = projectDebt(debt.outstandingBalance, debt.monthlyInterestRate, debt.installmentAmount + (Number(extra[debt.id]) || 0)); const normal = projectDebt(debt.outstandingBalance, debt.monthlyInterestRate, debt.installmentAmount); const reference = referenceFor(debt); const comparison = reference ? debt.monthlyInterestRate - reference.value : null; return <article className="panel debt-card" key={debt.id}><header><span><Landmark /></span><div><small>{debt.creditor || "Dívida cadastrada"}</small><h3>{debt.name}</h3></div><em className={debt.status.toLowerCase()}>{debtStatus(debt.status)}</em></header><div className="debt-balance"><span><small>Saldo devedor</small><strong>{money(debt.outstandingBalance)}</strong></span><span><small>Parcela atual</small><strong>{money(debt.installmentAmount)}</strong></span><span><small>Juros informados</small><strong>{debt.monthlyInterestRate}% a.m.</strong></span></div>{reference && <div className={`debt-reference ${comparison !== null && comparison > 0 ? "expensive" : ""}`}><Scale /><span><b>{comparison !== null && comparison > 0 ? `${comparison.toFixed(2)} p.p. acima da referência` : "Até a referência geral selecionada"}</b><small>{reference.name}: {reference.value}% a.m. · {reference.date.split("-").reverse().join("/")} · não é uma oferta de crédito</small></span></div>}<div className="debt-simulator"><label>Pagamento adicional mensal<input type="number" min="0" step="0.01" value={extra[debt.id] || ""} onChange={(event) => setExtra((current) => ({ ...current, [debt.id]: event.target.value }))} placeholder="0,00" /></label>{projection.payoffPossible ? <div><span><small>Prazo estimado</small><b>{projection.months} meses</b></span><span><small>Juros estimados</small><b>{money(projection.totalInterest || 0)}</b></span>{normal.payoffPossible && projection.months !== null && normal.months !== null && projection.months < normal.months && <span className="saving"><small>Redução estimada</small><b>{normal.months - projection.months} meses</b></span>}</div> : <p><CircleAlert />A parcela não cobre os juros mensais ou o prazo excede 50 anos.</p>}</div><div className="debt-actions"><input type="number" min="0.01" max={debt.outstandingBalance} step="0.01" value={payment[debt.id] || ""} onChange={(event) => setPayment((current) => ({ ...current, [debt.id]: event.target.value }))} placeholder="Valor pago" /><button disabled={pending} onClick={() => pay(debt)}>Registrar pagamento</button><select value={debt.status} onChange={(event) => status(debt, event.target.value as "ACTIVE" | "NEGOTIATING" | "DEFAULTED")}><option value="ACTIVE">Em dia</option><option value="NEGOTIATING">Em negociação</option><option value="DEFAULTED">Em atraso</option></select></div>{debt.payments[0] && <small className="last-payment">Último pagamento: {money(debt.payments[0].amount)} em {new Date(debt.payments[0].paidAt).toLocaleDateString("pt-BR")}</small>}</article>; })}</section>
    {adding && <DebtModal onClose={() => setAdding(false)} />}
  </div>;
}

function DebtModal({ onClose }: { onClose: () => void }) {
  const [state, action, pending] = useActionState(createDebt, {} as ActionState);
  useEffect(() => { if (state.success) window.location.reload(); }, [state.success]);
  return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><header><div><span className="kicker">CENTRAL DE DÍVIDAS</span><h2>Cadastrar dívida</h2></div><button className="icon-button" onClick={onClose}><X /></button></header><form action={action} className="transaction-form"><div className="form-grid"><label>Nome da dívida<input name="name" required autoFocus placeholder="Ex.: Empréstimo pessoal" /></label><label>Credor<input name="creditor" placeholder="Banco ou instituição" /></label><label>Valor original<input name="originalAmount" type="number" min="0.01" step="0.01" required /></label><label>Saldo devedor atual<input name="outstandingBalance" type="number" min="0.01" step="0.01" required /></label><label>Juros ao mês (%)<input name="monthlyInterestRate" type="number" min="0" max="100" step="0.0001" defaultValue="0" required /></label><label>Parcela mensal<input name="installmentAmount" type="number" min="0.01" step="0.01" required /></label><label>Pagamento mínimo<input name="minimumPayment" type="number" min="0.01" step="0.01" placeholder="Opcional" /></label><label>Dia do vencimento<input name="dueDay" type="number" min="1" max="31" placeholder="Opcional" /></label><label>Parcelas restantes<input name="remainingInstallments" type="number" min="1" max="600" placeholder="Opcional" /></label><label className="full">Observações<textarea name="notes" rows={2} /></label></div>{state.error && <p className="form-error">{state.error}</p>}<footer><button type="button" className="button secondary" onClick={onClose}>Cancelar</button><button className="button primary" disabled={pending}>{pending ? "Salvando…" : "Salvar dívida"}</button></footer></form></section></div>;
}
function debtStatus(value: string) { return ({ ACTIVE: "Em dia", NEGOTIATING: "Negociando", DEFAULTED: "Em atraso", PAID: "Quitada" } as Record<string, string>)[value] || value; }
