"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { ArrowRightLeft, Building2, Check, Link2, RefreshCw, ShieldCheck, Trash2, X } from "lucide-react";
import { importExternalTransaction, reviewTransactionMatch } from "@/app/actions";
import { money } from "@/lib/format";

type Connection = { id: string; provider: string; connectorName: string | null; status: string; consentExpiresAt: string | null; lastSyncAt: string | null; errorMessage: string | null; accounts: { id: string; name: string; type: string; currency: string; balance: number | null; creditLimit: number | null; transactionCount: number }[] };
type Match = { id: string; confidence: number; external: { id: string; description: string; amount: number; date: string; account: string; institution: string | null }; internal: { id: string; description: string; amount: number; date: string } | null };
type External = { id: string; description: string; amount: number; date: string; type: string; status: string; account: string; institution: string | null };

export function OpenFinancePanel({ connections, matches, unmatched }: { connections: Connection[]; matches: Match[]; unmatched: External[] }) {
  const router = useRouter();
  const [message, setMessage] = useState("");
  const [pending, startTransition] = useTransition();
  const bankBalance = connections.flatMap((item) => item.accounts).filter((item) => item.type === "BANK").reduce((sum, item) => sum + (item.balance || 0), 0);
  const creditBalance = connections.flatMap((item) => item.accounts).filter((item) => item.type === "CREDIT").reduce((sum, item) => sum + Math.max(item.balance || 0, 0), 0);
  async function connect() {
    setMessage("Preparando ambiente seguro de consentimento…");
    const response = await fetch("/api/open-finance/connect-token", { method: "POST" });
    const data = await response.json();
    if (!response.ok || !data.connectToken) return setMessage(data.error || "Open Finance não está configurado.");
    const { PluggyConnect } = await import("pluggy-connect-sdk");
    const widget = new PluggyConnect({ connectToken: data.connectToken, language: "pt", theme: "light", products: ["ACCOUNTS", "CREDIT_CARDS", "TRANSACTIONS", "LOANS", "INVESTMENTS"], onSuccess: async ({ item }) => { setMessage("Consentimento concluído. Sincronizando contas e movimentações…"); const stored = await fetch("/api/open-finance/connections", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ itemId: item.id }) }); const result = await stored.json(); setMessage(stored.ok ? `Sincronização concluída: ${result.accounts} contas e ${result.transactions} movimentações.` : result.error); router.refresh(); }, onError: (error) => setMessage(error.message || "A conexão não foi concluída.") });
    await widget.init();
  }
  function sync(id: string) { startTransition(async () => { setMessage("Sincronizando instituição…"); const response = await fetch(`/api/open-finance/connections/${id}/sync`, { method: "POST" }); const result = await response.json(); setMessage(response.ok ? `Sincronização concluída: ${result.transactions} movimentações verificadas.` : result.error); router.refresh(); }); }
  function revoke(id: string) { if (!window.confirm("Revogar esta conexão bancária? Os dados já sincronizados serão preservados para auditoria, mas não serão atualizados.")) return; startTransition(async () => { const response = await fetch(`/api/open-finance/connections/${id}`, { method: "DELETE" }); const result = await response.json(); setMessage(response.ok ? "Conexão revogada." : result.error); router.refresh(); }); }
  function review(id: string, decision: "CONFIRMED" | "REJECTED") { startTransition(async () => { const result = await reviewTransactionMatch(id, decision); setMessage(result.error || (decision === "CONFIRMED" ? "Correspondência confirmada." : "Sugestão descartada.")); router.refresh(); }); }
  function importRow(id: string) { startTransition(async () => { const result = await importExternalTransaction(id); setMessage(result.error || "Movimentação importada para o Finora. Revise cartão e categoria."); router.refresh(); }); }
  return <div className="banking-layout"><section className="planning-head banking-head"><div><span className="kicker light">CENTRAL BANCÁRIA AUTOMÁTICA</span><h2>{money(bankBalance - creditBalance)}</h2><p>posição líquida estimada das conexões sincronizadas</p></div><div><small>Saldo em contas</small><strong>{money(bankBalance)}</strong><button className="button primary" onClick={connect}><Link2 />Conectar instituição</button></div></section><div className="open-finance-safety"><ShieldCheck /><span><b>Você controla o consentimento.</b><small>Dados externos são preservados separadamente e só viram lançamentos após sua confirmação.</small></span></div>{message && <div className={/erro|não|indisponível/i.test(message) ? "notice danger" : "notice"}>{message}</div>}
    <section className="connection-grid">{connections.map((connection) => <article className="panel connection-card" key={connection.id}><header><span><Building2 /></span><div><small>{connection.provider}</small><h3>{connection.connectorName || "Instituição conectada"}</h3></div><em className={connection.status.toLowerCase()}>{connectionStatus(connection.status)}</em></header><div>{connection.accounts.map((account) => <div className="external-account" key={account.id}><span><b>{account.name}</b><small>{account.type === "CREDIT" ? "Cartão/crédito" : "Conta bancária"} · {account.transactionCount} movimentações</small></span><strong>{account.balance === null ? "Saldo não informado" : money(account.balance)}</strong></div>)}</div><footer><small>{connection.lastSyncAt ? `Atualizado em ${new Date(connection.lastSyncAt).toLocaleString("pt-BR")}` : "Aguardando primeira sincronização"}</small><button disabled={pending} onClick={() => sync(connection.id)}><RefreshCw />Sincronizar</button><button disabled={pending} onClick={() => revoke(connection.id)}><Trash2 />Revogar</button></footer>{connection.errorMessage && <p className="form-error">{connection.errorMessage}</p>}</article>)}</section>{!connections.length && <section className="panel empty-action"><span><Building2 /></span><b>Nenhuma instituição conectada</b><p>Quando a Pluggy estiver configurada, conecte bancos e cartões por consentimento Open Finance.</p><button className="button primary" onClick={connect}>Conectar primeira instituição</button></section>}
    <section className="panel match-panel"><div className="panel-heading"><div><span className="kicker">CONCILIAÇÃO INTELIGENTE</span><h2>Possíveis correspondências</h2></div></div>{matches.length ? <div className="match-list">{matches.map((match) => <article key={match.id}><div><small>Movimentação bancária · {match.external.account}</small><b>{match.external.description}</b><strong>{money(Math.abs(match.external.amount))}</strong></div><ArrowRightLeft /><div><small>Lançamento Finora</small><b>{match.internal?.description || "Sem candidato"}</b><strong>{match.internal ? money(match.internal.amount) : "—"}</strong></div><em>{Math.round(match.confidence * 100)}% compatível</em><footer><button disabled={pending} onClick={() => review(match.id, "REJECTED")}><X />Não corresponde</button><button disabled={pending} onClick={() => review(match.id, "CONFIRMED")}><Check />Confirmar</button></footer></article>)}</div> : <div className="empty">Nenhuma correspondência pendente de revisão.</div>}</section>
    <section className="panel external-panel"><div className="panel-heading"><div><span className="kicker">NOVAS MOVIMENTAÇÕES</span><h2>Disponíveis para importar</h2></div></div><div className="external-list">{unmatched.length ? unmatched.map((item) => <div key={item.id}><span><b>{item.description}</b><small>{item.institution || "Instituição"} · {item.account} · {new Date(item.date).toLocaleDateString("pt-BR")}</small></span><strong>{money(Math.abs(item.amount))}</strong><button disabled={pending} onClick={() => importRow(item.id)}>Importar</button></div>) : <div className="empty">Não há movimentações novas sem conciliação.</div>}</div></section>
  </div>;
}
function connectionStatus(status: string) { return ({ ACTIVE: "Ativa", SYNCING: "Sincronizando", REAUTH_REQUIRED: "Reconectar", REVOKED: "Revogada", ERROR: "Com erro", PENDING: "Pendente" } as Record<string, string>)[status] || status; }
